var express = require('express')
var router = express.Router()
var controllers = require('../controllers/')
router.get('/', controllers.sessionCheck, controllers.getRoot)
    .get('/register', controllers.sessionCheck, controllers.getRegister)
    .get('/login', controllers.sessionCheck, controllers.getLogin)
    .get('/home', controllers.checkAuth, controllers.getHome)
    .get('/logout', controllers.getLogout)
    .get('/photo_list', controllers.checkAuth, controllers.getPhotoList)
    .get('/photo', controllers.checkAuth, controllers.getPhoto)
    .get('/get_user_list', controllers.checkAuth, controllers.getUserList)
    .get('/favicon.ico', controllers.getFavicon)
    .get('/dp', controllers.getDp)
    .get('/profile', controllers.checkAuth, controllers.getProfile)
    .get('/profile/:what', controllers.checkAuth, controllers.getProfile)
    .get('/auth/google', controllers.passport.authenticate('google', {scope:['https://www.googleapis.com/auth/plus.login', 'profile', 'email']}))
    .get('/auth/google/callback', controllers.passport.authenticate('google', {failureRedirect:'/', scope:['https://www.googleapis.com/auth/plus.login', 'profile', 'email']}), (req, res)=>{
        console.log('****************************Authenticated')
        var user = req.session.passport.user
        req.session.user_email = user.email
        res.redirect('/home')
    })
    .get('/new_messages', controllers.checkAuth, controllers.getNewMessages)
    .post('/register', controllers.upload.none(), controllers.postRegister)
    .post('/login', controllers.upload.none(), controllers.postLogin)
    .post('/post_photo', controllers.checkAuth, controllers.postPhoto)
    .post('/like/:photo', controllers.checkAuth, controllers.postLike)
    .post('/profile', controllers.checkAuth, controllers.postProfile)
    .post('/chat_messages', controllers.checkAuth   , controllers.getChatHistory)
module.exports = router;